### ISSUE TITLE
Fix naming of sans family

### ISSUE THREAD

**Issue by ikanago** [ikanago/omekasy#21]

**Comment by famasoon** [comment]
I think the scope of this issue is the following.
```
Sans,
SansBold,
SansItalic,
SansBoldItalic,
```

What name do you plan to change to?
Maybe I can help.

**Comment by ikanago** [comment]
In other fonts, modifier like `Bold` comes before font name; for example, `Italic` and `BoldItalic`.
So sans family should be renamed like following:
```
Sans
BoldSans
ItalicSans
BoldItalicSans
```

I'm currently busy doing other stuff, so it will be helpful if you'd like to fix it. 🙏

**Comment by famasoon** [comment]
Thank you for your reply.
I got it, and I just create pull request.
Please check when you are free 🙏 

Regards,
Sakai
